#!/bin/sh

#TODO: ensure in pi_mc environent?

usage() {
  echo "Usage $0 [all|admin|client|worker]"
  exit 1
}

if [ $# -eq 0 ]
then
  ADMIN=false
  CLIENT=false
  WORKER=true
elif [ $# -eq 1 ]
then
  if [ $1 = 'all' ]
  then
    ADMIN=true
    CLIENT=true
    WORKER=true
  elif [ $1 = 'admin' ]
  then
    ADMIN=true
    CLIENT=false
    WORKER=false
  elif [ $1 = 'client' ]
  then
    ADMIN=false
    CLIENT=true
    WORKER=false
  elif [ $1 = 'worker' ]
  then
    ADMIN=false
    CLIENT=false
    WORKER=true
  else
    usage
  fi
else
  usage
fi

echo "admin: $ADMIN client: $CLIENT worker: $WORKER"

#ADMIN Block: Launch prometheus and ELK
if [ $ADMIN = true ]
then
  cd ~/pi_mc/server
  #sudo docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk --network=elknet sebp/elk
  sudo /bin/sh -c 'docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -d --name elk sebp/elk &'
  sudo -u prometheus /bin/sh -c '/usr/local/bin/prometheus --config.file="/etc/prometheus/prometheus.yml" --storage.tsdb.path="/var/lib/prometheus" &'  #port:9090

fi

if [ $WORKER = true ]
then
  cd ~/pi_mc/server
  docker stop  circle_svc
  docker rm circle_svc
  docker build -t="robert/circle" .
  docker run -d --add-host shale:192.168.1.7 -p 5000:5000 -p 8000:8000 --name=circle_svc robert/circle
fi

if [ $CLIENT = true ]
then
  echo "run client"
  cd ~/pi_mc/client
  python3 pi_coord.py
fi
